export const NavLinks = [
  { href: "/", key: "Inspiration", text: "Inspiration" },
  { href: "/", key: "Find Projects", text: "Find Projects" },
  { href: "/", key: "Learn Development", text: "Learn Development" },
  { href: "/", key: "Career Advancement", text: "Career Advancement" },
  { href: "/", key: "Hire Developers", text: "Hire Developers" },
];

export const categoryFilters = [
  "Frontend",
  "Backend",
  "Full-Stack",
  "Mobile",
  "UI/UX",
  "Game Dev",
  "DevOps",
  "Data Science",
  "Machine Learning",
  "Cybersecurity",
  "Blockchain",
  "E-commerce",
  "Chatbots",
];

export const footerLinks = [
  {
    title: "For Beginner",
    links: ["C", "C++", "JAVA", "Python", "JavaScript", "ReactJS", "NodeJS"],
  },
  {
    title: "Data Structures and Algorithm",
    links: [
      "Arrays",
      "Strings",
      "Bit Manipulation",
      "Recursion",
      "Divide and Conquer",
      "Time and Space Complexity",
      "Backtracking",
      "Linked List",
      "Stack",
      "Queue",
      "Hashing",
      "Binary Tree",
      "Binary Search Tree",
      "Heaps",
      "Tries",
      "Greedy Algorithms",
      "Graphs",
      "Dynamic Programming",
      "Segment Trees",
    ],
  },
  {
    title: "Machine Learning",
    links: [
      "Standard Scaler",
      "MinMax Scaler",
      "Undersampling",
      "Oversampling",
      "Naive Bayes",
      "Imputer",
      "Regression",
      "Classification",
      "Clustering",
      "KNN Imputer",
      "Decision Trees",
      "Naive Bayes",
      "Support Vector Machines",
      "Ensemble Learning Techniques",
    ],
  },
  {
    title: "Deep Learning",
    links: [
      "Neuron",
      "Weights",
      "Bias",
      "Activation Function",
      "Input and Output Layers",
      "Hidden layers",
      "Forward Propagation",
      "Backpropagation",
      "MLP",
      "Batches",
      "Epochs",
      "Dropout",
      "Normalization",
      "CNN",
      "RNN",
    ],
  },
  {
    title: "Social Links",
    links: [
      "Subscribe Us",
      "Facebook",
      "Instagram",
      "Linkedin",
      "Github",
      "AD's Profile",
    ],
  },
  {
    title: "Company",
    links: [
      "About",
      "Advertise with us",
      "Support",
      "Terms of service",
      "Privacy policy",
      "Cookie policy",
      "Contact Us",
    ],
  },
];
